server:
  port: 8888
spring:
  application:
    name: distrace-configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/FaelCrios/distrace-config
          default-label: master
          search-paths: "initial-service*"